sci-biology/seaview: version bump; add missing symlink so that the C++ header can be found; remove calll to xft-config and use pkg-config instead; set our Gentoo FLTK path (not include path) to /usr/include/fltk-1 so that svg.o gets included during linking, otherwise we get undefined reference to svg_tree_save(FD_nj_plot*)
(Portage version: 2.1.10.44/git/Linux x86_64, unsigned Manifest commit)