dev-java/hdf-java-2.8: fix hdfview script (quotes and sh-bang)
Add a sh-bang to the beginning of the script, because the user may not
be using a POSIX shell.

Remove redundant, escaped quotes around the java.library.path command
substitution.  With the quotes, the process uses a garbled Java path,
and you see errors like:

  java.lang.UnsatisfiedLinkError: no jhdf5 in java.library.path