sci-biology/abyss: tweak for gcc-6, bug #594254
Build failed as:
```
    In file included from AssemblyAlgorithms.cpp:4:0:
    ../DataLayer/FastaReader.h: In member function ‘FastaReader::operator void*() const’:
    ../DataLayer/FastaReader.h:49:35: error: cannot convert ‘std::istream {aka std::basic_istream<char>}’ to ‘void*’ ...
       operator void*() const { return m_in; }
                                       ^~~~
```

In the following source:

```c++
   static bool existFile(const char* f)
   {
        ifstream file(f);
        return file;
   }

```

c++98 provides file->operator void*()
c++11 provides file->explicit operator bool()

Hence the failure on c++11.

The change adds explicit casts around istream.

Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/594254

Package-Manager: portage-2.3.0